apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: ocb-positivepay-apirule
  labels:
    app: ocb-positivepay
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  service:
    name: ocb-positivepay-service
    port: 8080
    host: positivepay
  rules:
    - path: /.*
      methods: ["GET", "POST", "OPTIONS", "DELETE", "PUT", "HEAD"]
      accessStrategies:
        - handler: noop

