apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocb-positivepay-deployment
  labels:
    app: ocb-positivepay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocb-positivepay
  template:
    metadata:
      labels:
        app: ocb-positivepay
    spec:
      containers:
        - name: nginx
          image: docker.io/ocbdeveloper/ocb-extension-demo:v1.0.0
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: "/actuator/health"
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 10

---

apiVersion: v1
kind: Service
metadata:
  name: ocb-positivepay-service
  labels:
    app: ocb-positivepay
spec:
  selector:
    app: ocb-positivepay
  ports:
    - name: http
      port: 8080